title: Python exercises for biologists
description: A collection of exercises to learn Python for biologists
repository: ninanorgren/python-exercises
theme: jekyll-theme-cayman
github:
  is_project_page: false
