project:
  type: website


# several branches can be specified here
branches:
  - branch: "release-2025"     # change this to the release branch
    output-dir: "2025"         # change this to year and month of the course instance

website:
  title: "Python exercises for teaching biologists"
  sidebar:
    style: "floating"
    background: "#F4F6F6"
    fontsize: 30px
    search: true
    contents: 
      - index.qmd 
      - short.qmd
      - medium.qmd
      - long.qmd
  navbar:
    background: "#883B5A"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

