project:
  type: website
  resources:
    - h5p
    - assets

# several branches can be specified here
branches:
  - branch: "release-0000"     # change this to the release branch
    output-dir: "0000"         # change this to year and month of the course instance

website:
  title: "Course Title"
  sidebar:
    style: "floating"
    background: "#F4F6F6"
    fontsize: 30px
    search: true
    contents: 
      - index.qmd              # Update this to match your own pages
      - schedule.qmd
      - instructors.qmd
      - module1.qmd
      - module2.qmd
  navbar:
    background: "#A7C947"
    logo: "img/SciLifeLab_Logotype_NEG.png"
  favicon: "img/SciLifeLab_Logotype_NEG.png"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <script type="text/javascript" src="assets/h5p-standalone/dist/main.bundle.js"></script>
      - text: |
          <script type="text/javascript" src="static/js/h5p_code.js"></script>

execute:
  freeze: auto

