---
title: "Short exercises"
author: "Nina Norgren"
date: today
---

## Reverse complement DNA

::: {.callout-note}
### Information

**Level:** Easy  
**External libraries:** None  
**Time:** Short

:::

Reverse complementing a DNA sequence can for example be used to create sequences that interact with each other, for example in a PCR reaction. When reverse complementing, the sequence is first reversed, and then each base is exchanged with its complement:

A -> T  
T -> A  
G -> C   
C -> G  

For example: ATGTCGC becomes GCGACAT

**Exercise:**  
Given the DNA sequence below, write Python code to reverse complement it.

::: {.callout}
### Input data 

ATGGTCGAATGCGGTAACCGTAAATTGCGATCGCGCTAGGCCTAAACGTT

:::

::: {.callout collapse="true"}
### Answer
```{python}
#| echo: false
#| output: true

data = 'ATGGTCGAATGCGGTAACCGTAAATTGCGATCGCGCTAGGCCTAAACGTT'

code_dictionary = {'A': 'T',
                   'T': 'A',
                   'G': 'C',
                   'C': 'G'} 

reverse_sequence = data[::-1]
reverse_complement_list = []

for base in reverse_sequence:
    complement = code_dictionary[base]
    reverse_complement_list.append(complement)

reverse_complement_sequence = ''.join(reverse_complement_list)
reverse_complement_sequence

```
:::

<br>

## Calculate GC content

::: {.callout-note}
### Information

**Level:** Easy  
**External libraries:** None  
**Time:** Short

:::

Analysis of ancient DNA is getting more and more common, with better sequencing technologies available. It's common for ancient DNA sequences to have higher GC-content due to deamination of the A and T bases over time.

Someone has mixed up the DNA samples in the lab, and now they don't know which samples are ancient DNA and which are samples from modern time. Help identify the ancient DNA sequences by calculating the GC-content in each sequence, the higher number the more likely it being ancient DNA.

GC content is defined as the fraction of C or G bases in a sequence.

For example: ATGTACCG has a GC-content of 0.5

**Exercise:**  
Which of the following sequences could be ancient DNA?


::: {.callout}
### Input data 

Sequence A: ACGGCTGCCGGTGGCGGCCCGCGAATGCTTGCGC  
Sequence B: TTATGTCGCTTAGGATTGCTCGTCGCGTCGGAGA  
Sequence C: TTAGACAGCACGCTTGTGCGTAACGGACTCGCTA  
Sequence D: AAGCGGCTGTGCCGCGTGGTGCGATGCCGTCGCC  

:::

::: {.callout collapse="true"}
### Answer
```{python}
#| echo: false
#| output: true
seq_a = 'ACGGCTGCCGGTGGCGGCCCGCGAATGCTTGCGC'
seq_b = 'TTATGTCGCTTAGGATTGCTCGTCGCGTCGGAGA'
seq_c = 'TTAGACAGCACGCTTGTGCGTAACGGACTCGCTA'
seq_d = 'AAGCGGCTGTGCCGCGTGGTGCGATGCCGTCGCC'

seq_dictionary = {'Sequence A': seq_a,
                  'Sequence B': seq_b,
                  'Sequence C': seq_c,
                  'Sequence D': seq_d}

for sequence in seq_dictionary:
    gc_count = 0
    for base in seq_dictionary[sequence]:
        if base == 'G' or base == 'C':
            gc_count += 1
    gc_content = gc_count / len(seq_dictionary[sequence])
    print(f"{sequence} has GC content: {gc_content}")
```
Sequences A and D are more likely to be ancient DNA (However in reality the sequences are too short to draw any conclusions)

:::

<br>

## Translate RNA to protein

::: {.callout-note}
### Information

**Level:** Easy/Intermediate  
**External libraries:** None  
**Time:** Short

:::

Translation is the process of converting RNA sequences into protein sequences. Each group of three RNA bases (codon) corresponds to a specific amino acid. Below is the RNA codon table:

::: {.callout-caution collapse="true"}
### Codon table

|          |          |           |          |
|----------|----------|-----------|----------|
| UUU: F    |   CUU: L  |    AUU: I  |    GUU: V |
| UUC: F    |   CUC: L  |    AUC: I  |    GUC: V |
| UUA: L    |   CUA: L  |    AUA: I  |    GUA: V |
| UUG: L    |   CUG: L  |    AUG: M  |    GUG: V |
| UCU: S    |   CCU: P  |    ACU: T  |    GCU: A |
| UCC: S    |   CCC: P  |    ACC: T  |    GCC: A |
| UCA: S    |   CCA: P  |    ACA: T  |    GCA: A |
| UCG: S    |   CCG: P  |    ACG: T  |    GCG: A |
| UAU: Y    |   CAU: H  |    AAU: N  |    GAU: D |
| UAC: Y    |   CAC: H  |    AAC: N  |    GAC: D |
| UAA: Stop |   CAA: Q  |    AAA: K  |    GAA: E |
| UAG: Stop |   CAG: Q  |    AAG: K  |    GAG: E |
| UGU: C    |   CGU: R  |    AGU: S  |    GGU: G |
| UGC: C    |   CGC: R  |    AGC: S  |    GGC: G |
| UGA: Stop |   CGA: R  |    AGA: R  |    GGA: G |
| UGG: W    |   CGG: R  |    AGG: R  |    GGG: G |

:::

For example: AUGGCCAUGAAGGGC translates to MAMKG

**Exercise:** Given the RNA seuence below, write Python code to translate it to an amino acid sequence.

In this exercise you can ignore the stop codons as they do not appear in the input data.

::: {.callout}
### Input data 

AUGAAACAUUCAUUGGGCAGAAGGCGGGCAGAGAUACCCCCUUCGCUUAGGGGGGCAUAUUUUUGG

:::

::: {.callout collapse="true"}
### Answer
```{python}
#| echo: false
#| output: true
data = 'AUGAAACAUUCAUUGGGCAGAAGGCGGGCAGAGAUACCCCCUUCGCUUAGGGGGGCAUAUUUUUGG'

codon_table = {'UUU': 'F', 'UUC': 'F', 'UUA': 'L', 'UUG': 'L',
               'UCU': 'S', 'UCC': 'S', 'UCA': 'S', 'UCG': 'S',
               'UAU': 'Y', 'UAC': 'Y', 'UAA': 'Stop', 'UAG': 'Stop',
               'UGU': 'C', 'UGC': 'C', 'UGA': 'Stop', 'UGG': 'W',
               'CUU': 'L', 'CUC': 'L', 'CUA': 'L', 'CUG': 'L',
               'CCU': 'P', 'CCC': 'P', 'CCA': 'P', 'CCG': 'P',
               'CAU': 'H', 'CAC': 'H', 'CAA': 'Q', 'CAG': 'Q',
               'CGU': 'R', 'CGC': 'R', 'CGA': 'R', 'CGG': 'R',
               'AUU': 'I', 'AUC': 'I', 'AUA': 'I', 'AUG': 'M',
               'ACU': 'T', 'ACC': 'T', 'ACA': 'T', 'ACG': 'T',
               'AAU': 'N', 'AAC': 'N', 'AAA': 'K', 'AAG': 'K',
               'AGU': 'S', 'AGC': 'S', 'AGA': 'R', 'AGG': 'R',
               'GUU': 'V', 'GUC': 'V', 'GUA': 'V', 'GUG': 'V',
               'GCU': 'A', 'GCC': 'A', 'GCA': 'A', 'GCG': 'A',
               'GAU': 'D', 'GAC': 'D', 'GAA': 'E', 'GAG': 'E',
               'GGU': 'G', 'GGC': 'G', 'GGA': 'G', 'GGG': 'G'}

ix = 0
protein_sequence_list = []

while ix < len(data):
    codon = data[ix:ix+3]
    aminoacid = codon_table[codon]
    protein_sequence_list.append(aminoacid)
    ix += 3
    
protein_sequence = ''.join(protein_sequence_list)
protein_sequence
```

:::

<br>

## Find motifs in DNA

::: {.callout-note}
### Information

**Level:** Intermediate  
**External libraries:** None  
**Time:** Short
:::

Finding motifs in DNA is a common process in bioinformatics, one example could be to find binding sites for transcription factors. 

For example: ATCCT is a substring of CGATCCTGTCATCCTTCG starting in two different positions: 2 and 10.

**Exercise:** Given the DNA sequence and the query string below, in what starting positions is the query string a substring of the DNA sequence?

::: {.callout}
### Input data 

DNA sequence:   
CTGAGCCTGGACGCCTGAGCTACGCCTTGCGAAACGCGTTCGCCTGGCTAACCGCGCCTA  
query string:  
GCCT

:::

::: {.callout collapse="true"}
### Answer
```{python}
#| echo: false
#| output: true
data = 'CTGAGCCTGGACGCCTGAGCTACGCCTTGCGAAACGCGTTCGCCTGGCTAACCGCGCCTA'
query_string = 'GCCT'

ix = 0
query_position_result = []

while ix < len(data):
    if data[ix:].startswith(query_string):
        query_position_result.append(ix)
    ix += 1
    
query_position_result
```

:::

<br> 

## Amino acid frequency

::: {.callout-note}
### Information

**Level:** Easy  
**External libraries:** None  
**Time:** Short

:::

There are 20 common amino acids that are the building blocks of all proteins in our body. On of those proteins is Transthyretin (TTR), in which certain mutations causes Hereditary transthyretin amyloidosis, also known in Sweden as "Skellefteåsjukan".

**Exercise:**  
Given the protein sequence of TTR below, write Python code to count the frequencies of all the different amino acids in the sequence.

::: {.callout}
### Input data 

Protein sequence:  
MASHRLLLLCLAGLVFVSEAGPTGTGESKCPLMVKVLDAVRGSPAINVAVHVFRKAADDT  
WEPFASGKTSESGELHGLTTEEEFVEGIYKVEIDTKSYWKALGISPFHEHAEVVFTANDS  
GPRRYTIAALLSPYSYSTTAVVTNPKE

:::

::: {.callout collapse="true"}
### Answer
```{python}
#| echo: false
#| output: true
data = "MASHRLLLLCLAGLVFVSEAGPTGTGESKCPLMVKVLDAVRGSPAINVAVHVFRKAADDTWEPFASGKTSESGELHGLTTEEEFVEGIYKVEIDTKSYWKALGISPFHEHAEVVFTANDSGPRRYTIAALLSPYSYSTTAVVTNPKE"

frequencies = {}

for aa in data:
    if aa not in frequencies:
        frequencies[aa] = 0
    frequencies[aa] += 1
    
print(frequencies)
```

:::

<br>

## Filter low expressed genes

::: {.callout-note}
### Information

**Level:** Easy  
**External libraries:** None  
**Time:** Short

:::

RNA-seq data often contains genes with almost no reads. These should be filtered out in the pre-processing.

**Exercise:**  
Write a function that removes genes where the total number of reads summed over all samples is 30 or less, and returns a cleaned dictionary.

::: {.callout}
### Input data 

Each number in the list represent one sample:

counts = {  
    "GeneA": [5, 8, 2],  
    "GeneB": [300, 250, 400],  
    "GeneC": [0, 1, 0],  
    "GeneD": [40, 35, 50],  
}

:::

::: {.callout collapse="true"}
### Answer
```{python}
#| echo: false
#| output: true
counts = {
    "GeneA": [5, 8, 2],
    "GeneB": [300, 250, 400],
    "GeneC": [0, 1, 0],
    "GeneD": [40, 35, 50],
}

def filter_low_expressed_genes(gene_counts, limit):
    result = {}

    for gene in gene_counts:
        if sum(gene_counts[gene]) > limit:
            result[gene] = gene_counts[gene]
    return result

result = filter_low_expressed_genes(counts, 30)
result
```

:::

<br>


## Extract exons from fasta file

::: {.callout-note}
### Information

**Level:** Easy  
**External libraries:** None  
**Time:** Short

:::

Genes contains both exons and introns, with the exons being the part that is later translated into proteins. The FASTA file below contains the sequence for the HBB gene, with both exons and introns in it. In this case exons are represented by uppercase letters, and introns lowercase. Mutations in the HBB gene can cause sickle cell anemia. 

**Exercise:**  
Write pyton code that reads the fasta file and outputs the sequence with only exons in.

::: {.callout}
### Input data 

Download the FASTA file here: [HBB.fasta](https://nextcloud.dc.scilifelab.se/s/3stFFgHywiSqWp2/download)


:::

::: {.callout collapse="true"}
### Answer
```{python}
#| echo: false
#| output: true
fasta = open("solutions/supporting_files/HBB.fasta")

transcript = []

for line in fasta:
    if line.startswith(">"):
        continue
    for base in line:
        if base.isupper():
            transcript.append(base)
fasta.close()
''.join(transcript)
```

:::

<br>