---
title: "Calculate allele frequency"
author: "Nina Norgren"
date: today
---

## Background

The variant [rs12913832](https://www.snpedia.com/index.php/Rs12913832) is strongly associated with eye color. Persons with the AA or AG genotypes most likely have brown eyes, while persons with the GG genotypes most likely have blue eyes.   


## Goal

In this exercise the goal is to calculate the allele frequency of the rs12913832 variant from a VCF file, and plot the frequency of the different genotypes.

## Required materials

[Download a subset](https://nextcloud.dc.scilifelab.se/s/NbbymL3w8BPS2x7/download) of the 1000Genomes data, container 40 samples with variants on chromosome 15. For more information about the VCF format, see [here](https://samtools.github.io/hts-specs/VCFv4.3.pdf).

## Instructions

The rs12913832 SNP is located on chromosome 15, position 28365618 (genome build hg19). The VCF file you have downloaded contains a subset of variants on chromosome 15, that have been called using hg19.

### Get the allele counts

- Read the VCF file specifications to make sure you understand where the information you want is located
- Create a function that reads the VCF file and returns the line with the correct SNP 
- Create another function that parses that line and returns the counts for each genotype (AA, AG, GG) in a dictionary
- Tip! You can get the allele information from the VCF file

How many persons are likely blue-eyed?

::: {.callout collapse="true"}
### Answer
```{python}
#| echo: false
#| output: true
import requests, io
file_name = "https://nextcloud.dc.scilifelab.se/s/NbbymL3w8BPS2x7/download"
variant_position = '28365618'


def extract_variant_line(file_name, rs_position):
    r = requests.get(file_name)
    fh = io.StringIO(r.text)
    for line in fh:
        if line.startswith('#'):
            continue
        cols = line.strip().split()
        if cols[1] == rs_position:
            return line
        
def extract_genotypes(line):
    wt  = 0
    het = 0
    hom = 0

    cols = line.strip().split()
    zero = cols[3]
    one  = cols[4]
    for genotype in cols[9:]:
        if genotype == '0|0':
            wt += 1
        elif genotype == '0|1' or genotype == '1|0':
            het += 1
        elif genotype == '1|1':
            hom += 1
        else:
            print('found not matching', genotype)
    genotypes = { f"{zero}{zero}": wt
                , f"{zero}{one}": het
                , f"{one}{one}": hom }
    return genotypes


line = extract_variant_line(file_name, variant_position)
genotypes = extract_genotypes(line)
    
print(genotypes)
```

3 persons are most likely blue eyed. 

:::

### Plot the frequencies

Plot a bar plot with the frequencies of each genotype.

::: {.callout collapse="true"}
### Answer
```{python}
#| echo: false
#| output: true
from matplotlib import pyplot as plt

frequencies = {key: value/sum(genotypes.values()) for key, value in genotypes.items()}

plt.bar(frequencies.keys(), frequencies.values())
plt.show()
```


:::