---
title: "Calculate heterozygosity rate"
author: "Nina Norgren"
date: today
---

## Background

In genetics, heterozygosity refers to the presence of different alleles at a specific locus in an individual. At the population level, the heterozygosity rate for a SNP is the proportion of individuals who are heterozygous (e.g., genotype 0/1) at that position.

This measure can provide insight into genetic diversity within a population. Higher heterozygosity means more variation in the population at that SNP. 

## Goal

In this exercise the goal is to calculate the heterozygosity for the following SNPs using the data from a VCF file:

**12:75653012  
15:39836366  
22:46924596**


## Required materials

Download a VCF with 40 samples [here](https://nextcloud.dc.scilifelab.se/s/Y2QDnD3Ae9kr4dK/download). The file contains a subset of variants from chromosomes 12, 15, and 22. For more information about the VCF format, see [here](https://samtools.github.io/hts-specs/VCFv4.3.pdf).

<br>

## Instructions

Here we will approach the problem from it's smallest component we can break it down into. You can use the example inputs below to create the functions one by one, and in the end combine them with the input file.

### Create function for calculating heterozygosity

Create a Python function that takes a dictionary with allele frequencies as input, and outputs the heterozygosity rate.

**Example input:**  

`frequencies = {'0|0': 2, '0|1': 3, '1|0: 0', '1|1': 1}`
`calculate_heterozygosity(frequencies)`

::: {.callout-tip collapse="true"}
### Example output
```{python}
#| echo: false
#| output: true
frequencies = {'0|0': 2, '0|1': 3, '1|0': 0, '1|1': 1}

def calculate_heterozygosity(frequencies):
    heterozygots = frequencies['0|1'] + frequencies['1|0']
    total = sum(frequencies.values())
    return heterozygots / total
    
heterogyzosity_rate = calculate_heterozygosity(frequencies)
heterogyzosity_rate
```

:::



<br>

### Create a function that parses a line in a VCF file

Create a Python function that takes a data line from a VCF file as input (not the header lines), and parses out the allele frequencies for all samples in the file.

**Example input:**  
`line = 'chr1    346623     .       G       A       1451.38 PASS    AC=13;AF=0.325;AN=40   GT:AD:DP       0|0:15,1:16      0|0:16,0:16 0|1:15,12:28  0|1:15,5:20   0|1:18,5:23    1|1:3,21:24'`

::: {.callout-tip collapse="true"}
### Example output
```{python}
#| echo: false
#| output: true
line = 'chr1    346     .       G       A       1451.38 PASS    AC=13;AF=0.325;AN=40   GT:AD:DP       0|0:15,1:16      0|0:16,0:16 0|1:15,12:28  0|1:15,5:20   0|1:18,5:23    1|1:3,21:24'

def parse_allele_frequencies(line):
    frequencies = {'0|0': 0, '0|1': 0, '1|0': 0, '1|1': 0}
    entries = line.strip().split()
    for genotype in entries[9:]:
        alleles = genotype.split(':')[0]
        if alleles in frequencies:
            frequencies[alleles] += 1
        else:
            print(f"Found illegal character {alleles}, skipping")
    return frequencies
    
frequencies = parse_allele_frequencies(line)
frequencies
```

:::

<br>

### Create a function to read a VCF file
Create a Python function that takes a file path to the VCF file, plus a list of chromosome and location for SNPs as input (in the form chr:pos). The function should return a list of snp positions and lines, in the format: [(pos, line)].

**Function input:**

`positions = ['12:75653012', '15:39836366', '22:46924596']`
`extract_lines_from_vcf(1000G_subset_12_15_22_small.vcf, positions)`


::: {.callout-tip collapse="true"}
### Output
```{python}
#| echo: false
#| output: true
import requests, io
path_to_vcf = "https://nextcloud.dc.scilifelab.se/s/Y2QDnD3Ae9kr4dK/download"
positions = ['12:75653012', '15:39836366', '22:46924596']
                       
def extract_lines_from_vcf(vcf, positions):
    result_lines = []
    r = requests.get(vcf)
    fh = io.StringIO(r.text)
    for line in fh:
        if not line.startswith('#'):
            entries = line.strip().split()
            variant = f"{entries[0]}:{entries[1]}"
            if variant in positions:
                result_lines.append((variant, line))
    return result_lines
    
lines = extract_lines_from_vcf(path_to_vcf, positions)
print(lines)
```

:::

<br>

### Assemble previous functions
Assemble the functions all together and print the heterozygosity rate for the 3 SNPs.


::: {.callout-tip collapse="true"}
### Output
```{python}
#| echo: false
#| output: true
path_to_vcf = "https://nextcloud.dc.scilifelab.se/s/Y2QDnD3Ae9kr4dK/download"
positions = ['12:75653012', '15:39836366', '22:46924596']

lines = extract_lines_from_vcf(path_to_vcf, positions)
for line in lines:
    frequencies = parse_allele_frequencies(line[1])
    heterogyzosity_rate = calculate_heterozygosity(frequencies)
    print(f"heterozygosity rate for {line[0]}: {heterogyzosity_rate}")
```

:::